# Generated by Django 5.2.4 on 2025-08-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagehistory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagehistory',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='imagehistory',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
