# Generated by Django 5.2.4 on 2025-09-03 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagehistory', '0002_imagehistory_content_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagehistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_histories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagehistory',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='imagehistory',
            index=models.Index(fields=['original_filename'], name='imagehistor_origina_95e840_idx'),
        ),
        migrations.AddIndex(
            model_name='imagehistory',
            index=models.Index(fields=['user', 'content_hash'], name='imagehistor_user_id_337a10_idx'),
        ),
        migrations.AddConstraint(
            model_name='imagehistory',
            constraint=models.UniqueConstraint(fields=('user', 'content_hash'), name='uniq_user_content_hash'),
        ),
    ]
